# Generated by Django 5.2.7 on 2026-03-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duracion_estimada',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duración estimada'),
        ),
        migrations.AddField(
            model_name='job',
            name='habilidades_requeridas',
            field=models.CharField(blank=True, max_length=300, verbose_name='Habilidades requeridas'),
        ),
        migrations.AddField(
            model_name='job',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='trabajos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='remoto', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='requisitos',
            field=models.TextField(blank=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='job',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='job',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
