# Generated by Django 5.2.12 on 2026-03-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carrera',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Documento de identidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ubicación / Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foto_carnet',
            field=models.ImageField(blank=True, null=True, upload_to='carnets/', verbose_name='Foto del carnet estudiantil'),
        ),
        migrations.AddField(
            model_name='user',
            name='pregunta_seguridad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='respuesta_seguridad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('empleador', 'Necesito un trabajo hecho')], default='empleador', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='semestre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='universidad',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
