# Generated by Django 5.2.7 on 2026-05-20 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bug', 'Error en la app'), ('usuario', 'Reportar usuario'), ('pago', 'Problema con pago'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto')], default='abierto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_enviados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario reportado (opcional)')),
            ],
            options={
                'verbose_name': 'Ticket de soporte',
                'verbose_name_plural': 'Tickets de soporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
