# Generated by Django 5.2.7 on 2026-05-20 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('postulacion', 'Nueva postulación'), ('aceptado', 'Postulación aceptada'), ('rechazado', 'Postulación rechazada'), ('finalizado', 'Trabajo finalizado'), ('resena', 'Nueva reseña'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('mensaje', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
